# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-19 04:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('size', models.IntegerField()),
                ('arrival_time', models.DateTimeField(editable=False)),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('capacity', models.IntegerField(choices=[(2, 'two seater'), (4, 'four seater'), (8, 'eight seater')], default=2)),
                ('occupant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='queue.Party')),
            ],
        ),
        migrations.AddField(
            model_name='party',
            name='seat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='queue.Table'),
        ),
    ]
