# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-21 04:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
