# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 03:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0003_auto_20170322_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='party',
            options={'verbose_name_plural': 'parties'},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={},
        ),
    ]
