# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-03-23 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queue', '0004_auto_20170322_2057'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='number',
        ),
    ]
